name: Deploy Workflows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Commit and push changes
          run: |
            git config --global user.name ${{ secrets.USERNAME }}
            git config --global user.email ${{ secrets.EMAIL }}
    
            git add -A
            git commit -m "commit message"
            git push
